In [28]:
%pip install mlflow dagshub setuptools
%pip install --upgrade --force mlflow dagshub setuptools

Requirement already satisfied: mlflow in c:\users\hp\anaconda3\envs\atlas\lib\site-packages (2.15.0)
Requirement already satisfied: dagshub in c:\users\hp\anaconda3\envs\atlas\lib\site-packages (0.3.34)
Requirement already satisfied: setuptools in c:\users\hp\anaconda3\envs\atlas\lib\site-packages (82.0.0)
Requirement already satisfied: mlflow-skinny==2.15.0 in c:\users\hp\anaconda3\envs\atlas\lib\site-packages (from mlflow) (2.15.0)
Requirement already satisfied: Flask<4 in c:\users\hp\anaconda3\envs\atlas\lib\site-packages (from mlflow) (3.0.3)
Requirement already satisfied: alembic!=1.10.0,<2 in c:\users\hp\anaconda3\envs\atlas\lib\site-packages (from mlflow) (1.13.2)
Requirement already satisfied: docker<8,>=4.0.0 in c:\users\hp\anaconda3\envs\atlas\lib\site-packages (from mlflow) (7.1.0)
Requirement already satisfied: graphene<4 in c:\users\hp\anaconda3\envs\atlas\lib\site-packages (from mlflow) (3.3)
Requirement already satisfied: markdown<4,>=3.3 in c:\users\hp\anaconda3\envs\atlas\lib\site-packages (from mlflow) (3.6)
Requirement already satisfied: matplotlib<4 in c:\users\hp\anaconda3\envs\atlas\lib\site-packages (from mlflow) (3.10.8)
Requirement already satisfied: numpy<2 in c:\users\hp\anaconda3\envs\atlas\lib\site-packages (from mlflow) (1.26.4)
Requirement already satisfied: pandas<3 in c:\users\hp\anaconda3\envs\atlas\lib\site-packages (from mlflow) (2.2.2)
Requirement already satisfied: pyarrow<16,>=4.0.0 in c:\users\hp\anaconda3\envs\atlas\lib\site-packages (from mlflow) (15.0.2)
Requirement already satisfied: querystring-parser<2 in c:\users\hp\anaconda3\envs\atlas\lib\site-packages (from mlflow) (1.2.4)
Requirement already satisfied: scikit-learn<2 in c:\users\hp\anaconda3\envs\atlas\lib\site-packages (from mlflow) (1.5.1)
Requirement already satisfied: scipy<2 in c:\users\hp\anaconda3\envs\atlas\lib\site-packages (from mlflow) (1.14.0)
Requirement already satisfied: sqlalchemy<3,>=1.4.0 in c:\users\hp\anaconda3\envs\atlas\lib\site-packages (from mlflow) (2.0.31)
Requirement already satisfied: Jinja2<4,>=3.0 in c:\users\hp\anaconda3\envs\atlas\lib\site-packages (from mlflow) (3.1.4)
Requirement already satisfied: waitress<4 in c:\users\hp\anaconda3\envs\atlas\lib\site-packages (from mlflow) (3.0.0)
Requirement already satisfied: cachetools<6,>=5.0.0 in c:\users\hp\anaconda3\envs\atlas\lib\site-packages (from mlflow-skinny==2.15.0->mlflow) (5.4.0)
Requirement already satisfied: click<9,>=7.0 in c:\users\hp\anaconda3\envs\atlas\lib\site-packages (from mlflow-skinny==2.15.0->mlflow) (8.1.7)
Requirement already satisfied: cloudpickle<4 in c:\users\hp\anaconda3\envs\atlas\lib\site-packages (from mlflow-skinny==2.15.0->mlflow) (3.0.0)
Requirement already satisfied: databricks-sdk<1,>=0.20.0 in c:\users\hp\anaconda3\envs\atlas\lib\site-packages (from mlflow-skinny==2.15.0->mlflow) (0.29.0)
Requirement already satisfied: entrypoints<1 in c:\users\hp\anaconda3\envs\atlas\lib\site-packages (from mlflow-skinny==2.15.0->mlflow) (0.4)
Requirement already satisfied: gitpython<4,>=3.1.9 in c:\users\hp\anaconda3\envs\atlas\lib\site-packages (from mlflow-skinny==2.15.0->mlflow) (3.1.43)
Requirement already satisfied: importlib-metadata!=4.7.0,<8,>=3.7.0 in c:\users\hp\anaconda3\envs\atlas\lib\site-packages (from mlflow-skinny==2.15.0->mlflow) (7.2.1)
Requirement already satisfied: opentelemetry-api<3,>=1.9.0 in c:\users\hp\anaconda3\envs\atlas\lib\site-packages (from mlflow-skinny==2.15.0->mlflow) (1.26.0)
Requirement already satisfied: opentelemetry-sdk<3,>=1.9.0 in c:\users\hp\anaconda3\envs\atlas\lib\site-packages (from mlflow-skinny==2.15.0->mlflow) (1.26.0)
Requirement already satisfied: packaging<25 in c:\users\hp\anaconda3\envs\atlas\lib\site-packages (from mlflow-skinny==2.15.0->mlflow) (24.1)
Requirement already satisfied: protobuf<6,>=3.12.0 in c:\users\hp\anaconda3\envs\atlas\lib\site-packages (from mlflow-skinny==2.15.0->mlflow) (5.27.3)
Requirement already satisfied: pytz<2025 in c:\users\hp\anaconda3\envs\atlas\lib\site-packages (from mlflow-skinny==2.15.0->mlflow) (2024.1)
Requirement already satisfied: pyyaml<7,>=5.1 in c:\users\hp\anaconda3\envs\atlas\lib\site-packages (from mlflow-skinny==2.15.0->mlflow) (6.0.1)
Requirement already satisfied: requests<3,>=2.17.3 in c:\users\hp\anaconda3\envs\atlas\lib\site-packages (from mlflow-skinny==2.15.0->mlflow) (2.32.3)
Requirement already satisfied: sqlparse<1,>=0.4.0 in c:\users\hp\anaconda3\envs\atlas\lib\site-packages (from mlflow-skinny==2.15.0->mlflow) (0.5.1)
Requirement already satisfied: Mako in c:\users\hp\anaconda3\envs\atlas\lib\site-packages (from alembic!=1.10.0,<2->mlflow) (1.3.5)
Requirement already satisfied: typing-extensions>=4 in c:\users\hp\anaconda3\envs\atlas\lib\site-packages (from alembic!=1.10.0,<2->mlflow) (4.12.2)
Requirement already satisfied: colorama in c:\users\hp\anaconda3\envs\atlas\lib\site-packages (from click<9,>=7.0->mlflow-skinny==2.15.0->mlflow) (0.4.6)
Requirement already satisfied: google-auth~=2.0 in c:\users\hp\anaconda3\envs\atlas\lib\site-packages (from databricks-sdk<1,>=0.20.0->mlflow-skinny==2.15.0->mlflow) (2.32.0)
Requirement already satisfied: pywin32>=304 in c:\users\hp\anaconda3\envs\atlas\lib\site-packages (from docker<8,>=4.0.0->mlflow) (311)
Requirement already satisfied: urllib3>=1.26.0 in c:\users\hp\anaconda3\envs\atlas\lib\site-packages (from docker<8,>=4.0.0->mlflow) (2.2.2)
Requirement already satisfied: Werkzeug>=3.0.0 in c:\users\hp\anaconda3\envs\atlas\lib\site-packages (from Flask<4->mlflow) (3.0.3)
Requirement already satisfied: itsdangerous>=2.1.2 in c:\users\hp\anaconda3\envs\atlas\lib\site-packages (from Flask<4->mlflow) (2.2.0)
Requirement already satisfied: blinker>=1.6.2 in c:\users\hp\anaconda3\envs\atlas\lib\site-packages (from Flask<4->mlflow) (1.8.2)
Requirement already satisfied: gitdb<5,>=4.0.1 in c:\users\hp\anaconda3\envs\atlas\lib\site-packages (from gitpython<4,>=3.1.9->mlflow-skinny==2.15.0->mlflow) (4.0.11)
Requirement already satisfied: smmap<6,>=3.0.1 in c:\users\hp\anaconda3\envs\atlas\lib\site-packages (from gitdb<5,>=4.0.1->gitpython<4,>=3.1.9->mlflow-skinny==2.15.0->mlflow) (5.0.1)
Requirement already satisfied: pyasn1-modules>=0.2.1 in c:\users\hp\anaconda3\envs\atlas\lib\site-packages (from google-auth~=2.0->databricks-sdk<1,>=0.20.0->mlflow-skinny==2.15.0->mlflow) (0.4.0)
Requirement already satisfied: rsa<5,>=3.1.4 in c:\users\hp\anaconda3\envs\atlas\lib\site-packages (from google-auth~=2.0->databricks-sdk<1,>=0.20.0->mlflow-skinny==2.15.0->mlflow) (4.7.2)
Requirement already satisfied: graphql-core<3.3,>=3.1 in c:\users\hp\anaconda3\envs\atlas\lib\site-packages (from graphene<4->mlflow) (3.2.3)
Requirement already satisfied: graphql-relay<3.3,>=3.1 in c:\users\hp\anaconda3\envs\atlas\lib\site-packages (from graphene<4->mlflow) (3.2.0)
Requirement already satisfied: aniso8601<10,>=8 in c:\users\hp\anaconda3\envs\atlas\lib\site-packages (from graphene<4->mlflow) (9.0.1)
Requirement already satisfied: zipp>=0.5 in c:\users\hp\anaconda3\envs\atlas\lib\site-packages (from importlib-metadata!=4.7.0,<8,>=3.7.0->mlflow-skinny==2.15.0->mlflow) (3.19.2)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\hp\anaconda3\envs\atlas\lib\site-packages (from Jinja2<4,>=3.0->mlflow) (2.1.5)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\hp\anaconda3\envs\atlas\lib\site-packages (from matplotlib<4->mlflow) (1.2.1)
Requirement already satisfied: cycler>=0.10 in c:\users\hp\anaconda3\envs\atlas\lib\site-packages (from matplotlib<4->mlflow) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\hp\anaconda3\envs\atlas\lib\site-packages (from matplotlib<4->mlflow) (4.53.1)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\hp\anaconda3\envs\atlas\lib\site-packages (from matplotlib<4->mlflow) (1.4.5)
Requirement already satisfied: pillow>=8 in c:\users\hp\anaconda3\envs\atlas\lib\site-packages (from matplotlib<4->mlflow) (10.4.0)
Requirement already satisfied: pyparsing>=3 in c:\users\hp\anaconda3\envs\atlas\lib\site-packages (from matplotlib<4->mlflow) (3.1.2)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\hp\anaconda3\envs\atlas\lib\site-packages (from matplotlib<4->mlflow) (2.9.0.post0)
Requirement already satisfied: deprecated>=1.2.6 in c:\users\hp\anaconda3\envs\atlas\lib\site-packages (from opentelemetry-api<3,>=1.9.0->mlflow-skinny==2.15.0->mlflow) (1.2.14)
Requirement already satisfied: opentelemetry-semantic-conventions==0.47b0 in c:\users\hp\anaconda3\envs\atlas\lib\site-packages (from opentelemetry-sdk<3,>=1.9.0->mlflow-skinny==2.15.0->mlflow) (0.47b0)
Requirement already satisfied: tzdata>=2022.7 in c:\users\hp\anaconda3\envs\atlas\lib\site-packages (from pandas<3->mlflow) (2024.1)
Requirement already satisfied: six in c:\users\hp\anaconda3\envs\atlas\lib\site-packages (from querystring-parser<2->mlflow) (1.16.0)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\hp\anaconda3\envs\atlas\lib\site-packages (from requests<3,>=2.17.3->mlflow-skinny==2.15.0->mlflow) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\hp\anaconda3\envs\atlas\lib\site-packages (from requests<3,>=2.17.3->mlflow-skinny==2.15.0->mlflow) (3.7)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\hp\anaconda3\envs\atlas\lib\site-packages (from requests<3,>=2.17.3->mlflow-skinny==2.15.0->mlflow) (2024.7.4)
Requirement already satisfied: pyasn1>=0.1.3 in c:\users\hp\anaconda3\envs\atlas\lib\site-packages (from rsa<5,>=3.1.4->google-auth~=2.0->databricks-sdk<1,>=0.20.0->mlflow-skinny==2.15.0->mlflow) (0.6.0)
Requirement already satisfied: joblib>=1.2.0 in c:\users\hp\anaconda3\envs\atlas\lib\site-packages (from scikit-learn<2->mlflow) (1.4.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\users\hp\anaconda3\envs\atlas\lib\site-packages (from scikit-learn<2->mlflow) (3.5.0)
Requirement already satisfied: greenlet!=0.4.17 in c:\users\hp\anaconda3\envs\atlas\lib\site-packages (from sqlalchemy<3,>=1.4.0->mlflow) (3.0.3)
Requirement already satisfied: fusepy>=3 in c:\users\hp\anaconda3\envs\atlas\lib\site-packages (from dagshub) (3.0.1)
Requirement already satisfied: appdirs>=1.4.4 in c:\users\hp\anaconda3\envs\atlas\lib\site-packages (from dagshub) (1.4.4)
Requirement already satisfied: httpx~=0.23.0 in c:\users\hp\anaconda3\envs\atlas\lib\site-packages (from dagshub) (0.23.3)
Requirement already satisfied: rich~=13.1.0 in c:\users\hp\anaconda3\envs\atlas\lib\site-packages (from dagshub) (13.1.0)
Requirement already satisfied: dacite~=1.6.0 in c:\users\hp\anaconda3\envs\atlas\lib\site-packages (from dagshub) (1.6.0)
Requirement already satisfied: tenacity~=8.2.2 in c:\users\hp\anaconda3\envs\atlas\lib\site-packages (from dagshub) (8.2.3)
Requirement already satisfied: gql[requests] in c:\users\hp\anaconda3\envs\atlas\lib\site-packages (from dagshub) (3.5.0)
Requirement already satisfied: dataclasses-json in c:\users\hp\anaconda3\envs\atlas\lib\site-packages (from dagshub) (0.6.7)
Requirement already satisfied: treelib~=1.6.4 in c:\users\hp\anaconda3\envs\atlas\lib\site-packages (from dagshub) (1.6.4)
Requirement already satisfied: pathvalidate~=3.0.0 in c:\users\hp\anaconda3\envs\atlas\lib\site-packages (from dagshub) (3.0.0)
Requirement already satisfied: boto3 in c:\users\hp\anaconda3\envs\atlas\lib\site-packages (from dagshub) (1.34.131)
Requirement already satisfied: httpcore<0.17.0,>=0.15.0 in c:\users\hp\anaconda3\envs\atlas\lib\site-packages (from httpx~=0.23.0->dagshub) (0.16.3)
Requirement already satisfied: rfc3986<2,>=1.3 in c:\users\hp\anaconda3\envs\atlas\lib\site-packages (from rfc3986[idna2008]<2,>=1.3->httpx~=0.23.0->dagshub) (1.5.0)
Requirement already satisfied: sniffio in c:\users\hp\anaconda3\envs\atlas\lib\site-packages (from httpx~=0.23.0->dagshub) (1.3.1)
Requirement already satisfied: h11<0.15,>=0.13 in c:\users\hp\anaconda3\envs\atlas\lib\site-packages (from httpcore<0.17.0,>=0.15.0->httpx~=0.23.0->dagshub) (0.14.0)
Requirement already satisfied: anyio<5.0,>=3.0 in c:\users\hp\anaconda3\envs\atlas\lib\site-packages (from httpcore<0.17.0,>=0.15.0->httpx~=0.23.0->dagshub) (4.4.0)
Requirement already satisfied: exceptiongroup>=1.0.2 in c:\users\hp\anaconda3\envs\atlas\lib\site-packages (from anyio<5.0,>=3.0->httpcore<0.17.0,>=0.15.0->httpx~=0.23.0->dagshub) (1.3.1)
Requirement already satisfied: commonmark<0.10.0,>=0.9.0 in c:\users\hp\anaconda3\envs\atlas\lib\site-packages (from rich~=13.1.0->dagshub) (0.9.1)
Requirement already satisfied: pygments<3.0.0,>=2.6.0 in c:\users\hp\anaconda3\envs\atlas\lib\site-packages (from rich~=13.1.0->dagshub) (2.18.0)
Requirement already satisfied: wrapt<2,>=1.10 in c:\users\hp\anaconda3\envs\atlas\lib\site-packages (from deprecated>=1.2.6->opentelemetry-api<3,>=1.9.0->mlflow-skinny==2.15.0->mlflow) (1.16.0)
Requirement already satisfied: botocore<1.35.0,>=1.34.131 in c:\users\hp\anaconda3\envs\atlas\lib\site-packages (from boto3->dagshub) (1.34.162)
Requirement already satisfied: jmespath<2.0.0,>=0.7.1 in c:\users\hp\anaconda3\envs\atlas\lib\site-packages (from boto3->dagshub) (1.0.1)
Requirement already satisfied: s3transfer<0.11.0,>=0.10.0 in c:\users\hp\anaconda3\envs\atlas\lib\site-packages (from boto3->dagshub) (0.10.2)
Requirement already satisfied: marshmallow<4.0.0,>=3.18.0 in c:\users\hp\anaconda3\envs\atlas\lib\site-packages (from dataclasses-json->dagshub) (3.21.3)
Requirement already satisfied: typing-inspect<1,>=0.4.0 in c:\users\hp\anaconda3\envs\atlas\lib\site-packages (from dataclasses-json->dagshub) (0.9.0)
Requirement already satisfied: mypy-extensions>=0.3.0 in c:\users\hp\anaconda3\envs\atlas\lib\site-packages (from typing-inspect<1,>=0.4.0->dataclasses-json->dagshub) (1.0.0)
Requirement already satisfied: yarl<2.0,>=1.6 in c:\users\hp\anaconda3\envs\atlas\lib\site-packages (from gql[requests]->dagshub) (1.9.4)
Requirement already satisfied: backoff<3.0,>=1.11.1 in c:\users\hp\anaconda3\envs\atlas\lib\site-packages (from gql[requests]->dagshub) (2.2.1)
Requirement already satisfied: requests-toolbelt<2,>=1.0.0 in c:\users\hp\anaconda3\envs\atlas\lib\site-packages (from gql[requests]->dagshub) (1.0.0)
Requirement already satisfied: multidict>=4.0 in c:\users\hp\anaconda3\envs\atlas\lib\site-packages (from yarl<2.0,>=1.6->gql[requests]->dagshub) (6.0.5)
Note: you may need to restart the kernel to use updated packages.
Collecting mlflow
  Downloading mlflow-3.10.0-py3-none-any.whl.metadata (31 kB)
Collecting dagshub
  Downloading dagshub-0.6.8-py3-none-any.whl.metadata (12 kB)
Collecting setuptools
  Using cached setuptools-82.0.0-py3-none-any.whl.metadata (6.6 kB)
Collecting mlflow-skinny==3.10.0 (from mlflow)
  Downloading mlflow_skinny-3.10.0-py3-none-any.whl.metadata (32 kB)
Collecting mlflow-tracing==3.10.0 (from mlflow)
  Downloading mlflow_tracing-3.10.0-py3-none-any.whl.metadata (19 kB)
Collecting Flask-CORS<7 (from mlflow)
  Using cached flask_cors-6.0.2-py3-none-any.whl.metadata (5.3 kB)
Collecting Flask<4 (from mlflow)
  Downloading flask-3.1.3-py3-none-any.whl.metadata (3.2 kB)
Collecting alembic!=1.10.0,<2 (from mlflow)
  Downloading alembic-1.18.4-py3-none-any.whl.metadata (7.2 kB)
Collecting cryptography<47,>=43.0.0 (from mlflow)
  Downloading cryptography-46.0.5-cp38-abi3-win_amd64.whl.metadata (5.7 kB)
Collecting docker<8,>=4.0.0 (from mlflow)
  Using cached docker-7.1.0-py3-none-any.whl.metadata (3.8 kB)
Collecting graphene<4 (from mlflow)
  Using cached graphene-3.4.3-py2.py3-none-any.whl.metadata (6.9 kB)
Collecting huey<3,>=2.5.4 (from mlflow)
  Using cached huey-2.6.0-py3-none-any.whl.metadata (4.3 kB)
Collecting matplotlib<4 (from mlflow)
  Using cached matplotlib-3.10.8-cp310-cp310-win_amd64.whl.metadata (52 kB)
Collecting numpy<3 (from mlflow)
  Using cached numpy-2.2.6-cp310-cp310-win_amd64.whl.metadata (60 kB)
Collecting pandas<3 (from mlflow)
  Using cached pandas-2.3.3-cp310-cp310-win_amd64.whl.metadata (19 kB)
Collecting pyarrow<24,>=4.0.0 (from mlflow)
  Downloading pyarrow-23.0.1-cp310-cp310-win_amd64.whl.metadata (3.1 kB)
Collecting scikit-learn<2 (from mlflow)
  Using cached scikit_learn-1.7.2-cp310-cp310-win_amd64.whl.metadata (11 kB)
Collecting scipy<2 (from mlflow)
  Using cached scipy-1.15.3-cp310-cp310-win_amd64.whl.metadata (60 kB)
Collecting skops<1 (from mlflow)
  Using cached skops-0.13.0-py3-none-any.whl.metadata (5.6 kB)
Collecting sqlalchemy<3,>=1.4.0 (from mlflow)
  Downloading sqlalchemy-2.0.47-cp310-cp310-win_amd64.whl.metadata (9.8 kB)
Collecting waitress<4 (from mlflow)
  Using cached waitress-3.0.2-py3-none-any.whl.metadata (5.8 kB)
Collecting cachetools<8,>=5.0.0 (from mlflow-skinny==3.10.0->mlflow)
  Downloading cachetools-7.0.1-py3-none-any.whl.metadata (5.6 kB)
Collecting click<9,>=7.0 (from mlflow-skinny==3.10.0->mlflow)
  Using cached click-8.3.1-py3-none-any.whl.metadata (2.6 kB)
Collecting cloudpickle<4 (from mlflow-skinny==3.10.0->mlflow)
  Using cached cloudpickle-3.1.2-py3-none-any.whl.metadata (7.1 kB)
Collecting databricks-sdk<1,>=0.20.0 (from mlflow-skinny==3.10.0->mlflow)
  Downloading databricks_sdk-0.94.0-py3-none-any.whl.metadata (40 kB)
Collecting fastapi<1 (from mlflow-skinny==3.10.0->mlflow)
  Downloading fastapi-0.134.0-py3-none-any.whl.metadata (30 kB)
Collecting gitpython<4,>=3.1.9 (from mlflow-skinny==3.10.0->mlflow)
  Using cached gitpython-3.1.46-py3-none-any.whl.metadata (13 kB)
Collecting importlib_metadata!=4.7.0,<9,>=3.7.0 (from mlflow-skinny==3.10.0->mlflow)
  Using cached importlib_metadata-8.7.1-py3-none-any.whl.metadata (4.7 kB)
Collecting opentelemetry-api<3,>=1.9.0 (from mlflow-skinny==3.10.0->mlflow)
  Using cached opentelemetry_api-1.39.1-py3-none-any.whl.metadata (1.5 kB)
Collecting opentelemetry-proto<3,>=1.9.0 (from mlflow-skinny==3.10.0->mlflow)
  Using cached opentelemetry_proto-1.39.1-py3-none-any.whl.metadata (2.3 kB)
Collecting opentelemetry-sdk<3,>=1.9.0 (from mlflow-skinny==3.10.0->mlflow)
  Using cached opentelemetry_sdk-1.39.1-py3-none-any.whl.metadata (1.5 kB)
Collecting packaging<27 (from mlflow-skinny==3.10.0->mlflow)
  Using cached packaging-26.0-py3-none-any.whl.metadata (3.3 kB)
Collecting protobuf<7,>=3.12.0 (from mlflow-skinny==3.10.0->mlflow)
  Using cached protobuf-6.33.5-cp310-abi3-win_amd64.whl.metadata (593 bytes)
Collecting pydantic<3,>=2.0.0 (from mlflow-skinny==3.10.0->mlflow)
  Using cached pydantic-2.12.5-py3-none-any.whl.metadata (90 kB)
Collecting python-dotenv<2,>=0.19.0 (from mlflow-skinny==3.10.0->mlflow)
  Using cached python_dotenv-1.2.1-py3-none-any.whl.metadata (25 kB)
Collecting pyyaml<7,>=5.1 (from mlflow-skinny==3.10.0->mlflow)
  Using cached pyyaml-6.0.3-cp310-cp310-win_amd64.whl.metadata (2.4 kB)
Collecting requests<3,>=2.17.3 (from mlflow-skinny==3.10.0->mlflow)
  Using cached requests-2.32.5-py3-none-any.whl.metadata (4.9 kB)
Collecting sqlparse<1,>=0.4.0 (from mlflow-skinny==3.10.0->mlflow)
  Using cached sqlparse-0.5.5-py3-none-any.whl.metadata (4.7 kB)
Collecting typing-extensions<5,>=4.0.0 (from mlflow-skinny==3.10.0->mlflow)
  Using cached typing_extensions-4.15.0-py3-none-any.whl.metadata (3.3 kB)
Collecting uvicorn<1 (from mlflow-skinny==3.10.0->mlflow)
  Using cached uvicorn-0.41.0-py3-none-any.whl.metadata (6.7 kB)
Collecting Mako (from alembic!=1.10.0,<2->mlflow)
  Using cached mako-1.3.10-py3-none-any.whl.metadata (2.9 kB)
Collecting tomli (from alembic!=1.10.0,<2->mlflow)
  Using cached tomli-2.4.0-py3-none-any.whl.metadata (10 kB)
Collecting colorama (from click<9,>=7.0->mlflow-skinny==3.10.0->mlflow)
  Using cached colorama-0.4.6-py2.py3-none-any.whl.metadata (17 kB)
Collecting cffi>=2.0.0 (from cryptography<47,>=43.0.0->mlflow)
  Using cached cffi-2.0.0-cp310-cp310-win_amd64.whl.metadata (2.6 kB)
Collecting google-auth~=2.0 (from databricks-sdk<1,>=0.20.0->mlflow-skinny==3.10.0->mlflow)
  Using cached google_auth-2.48.0-py3-none-any.whl.metadata (6.2 kB)
Collecting pywin32>=304 (from docker<8,>=4.0.0->mlflow)

  WARNING: Failed to remove contents in a temporary directory 'C:\Users\Hp\anaconda3\envs\atlas\Lib\site-packages\~aml'.
  You can safely remove it manually.
  WARNING: Failed to remove contents in a temporary directory 'C:\Users\Hp\anaconda3\envs\atlas\Lib\site-packages\~yarrow'.
  You can safely remove it manually.
  WARNING: Failed to remove contents in a temporary directory 'C:\Users\Hp\anaconda3\envs\atlas\Lib\site-packages\google\~upb'.
  You can safely remove it manually.
  WARNING: Failed to remove contents in a temporary directory 'C:\Users\Hp\anaconda3\envs\atlas\Lib\site-packages\~umpy.libs'.
  You can safely remove it manually.
  WARNING: Failed to remove contents in a temporary directory 'C:\Users\Hp\anaconda3\envs\atlas\Lib\site-packages\~umpy'.
  You can safely remove it manually.
  WARNING: Failed to remove contents in a temporary directory 'C:\Users\Hp\anaconda3\envs\atlas\Lib\site-packages\~harset_normalizer'.
  You can safely remove it manually.
  WARNING: Failed to remove contents in a temporary directory 'C:\Users\Hp\anaconda3\envs\atlas\Lib\site-packages\~cipy.libs'.
  You can safely remove it manually.
  WARNING: Failed to remove contents in a temporary directory 'C:\Users\Hp\anaconda3\envs\atlas\Lib\site-packages\~cipy'.
  You can safely remove it manually.
  WARNING: Failed to remove contents in a temporary directory 'C:\Users\Hp\anaconda3\envs\atlas\Lib\site-packages\~klearn'.
  You can safely remove it manually.
  WARNING: Failed to remove contents in a temporary directory 'C:\Users\Hp\anaconda3\envs\atlas\Lib\site-packages\~andas.libs'.
  You can safely remove it manually.
  WARNING: Failed to remove contents in a temporary directory 'C:\Users\Hp\anaconda3\envs\atlas\Lib\site-packages\~andas'.
  You can safely remove it manually.
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
aiobotocore 2.13.3 requires botocore<1.34.163,>=1.34.70, but you have botocore 1.42.59 which is incompatible.

Collecting cycler>=0.10 (from matplotlib<4->mlflow)
  Using cached cycler-0.12.1-py3-none-any.whl.metadata (3.8 kB)
Collecting fonttools>=4.22.0 (from matplotlib<4->mlflow)
  Using cached fonttools-4.61.1-cp310-cp310-win_amd64.whl.metadata (116 kB)
Collecting kiwisolver>=1.3.1 (from matplotlib<4->mlflow)
  Using cached kiwisolver-1.4.9-cp310-cp310-win_amd64.whl.metadata (6.4 kB)
Collecting pillow>=8 (from matplotlib<4->mlflow)
  Using cached pillow-12.1.1-cp310-cp310-win_amd64.whl.metadata (9.0 kB)
Collecting pyparsing>=3 (from matplotlib<4->mlflow)
  Using cached pyparsing-3.3.2-py3-none-any.whl.metadata (5.8 kB)
Collecting opentelemetry-semantic-conventions==0.60b1 (from opentelemetry-sdk<3,>=1.9.0->mlflow-skinny==3.10.0->mlflow)
  Using cached opentelemetry_semantic_conventions-0.60b1-py3-none-any.whl.metadata (2.4 kB)
Collecting pytz>=2020.1 (from pandas<3->mlflow)
  Using cached pytz-2025.2-py2.py3-none-any.whl.metadata (22 kB)
Collecting tzdata>=2022.7 (from pandas<3->mlflow)
  Using cached tzdata-2025.3-py2.py3-none-any.whl.metadata (1.4 kB)
Collecting annotated-types>=0.6.0 (from pydantic<3,>=2.0.0->mlflow-skinny==3.10.0->mlflow)
  Using cached annotated_types-0.7.0-py3-none-any.whl.metadata (15 kB)
Collecting pydantic-core==2.41.5 (from pydantic<3,>=2.0.0->mlflow-skinny==3.10.0->mlflow)
  Using cached pydantic_core-2.41.5-cp310-cp310-win_amd64.whl.metadata (7.4 kB)
Collecting six>=1.5 (from python-dateutil<3,>=2.7.0->graphene<4->mlflow)
  Using cached six-1.17.0-py2.py3-none-any.whl.metadata (1.7 kB)
Collecting charset_normalizer<4,>=2 (from requests<3,>=2.17.3->mlflow-skinny==3.10.0->mlflow)
  Using cached charset_normalizer-3.4.4-cp310-cp310-win_amd64.whl.metadata (38 kB)
Collecting idna<4,>=2.5 (from requests<3,>=2.17.3->mlflow-skinny==3.10.0->mlflow)
  Using cached idna-3.11-py3-none-any.whl.metadata (8.4 kB)
Collecting certifi>=2017.4.17 (from requests<3,>=2.17.3->mlflow-skinny==3.10.0->mlflow)
  Using cached certifi-2026.2.25-py3-none-any.whl.metadata (2.5 kB)
Collecting pyasn1>=0.1.3 (from rsa<5,>=3.1.4->google-auth~=2.0->databricks-sdk<1,>=0.20.0->mlflow-skinny==3.10.0->mlflow)
  Using cached pyasn1-0.6.2-py3-none-any.whl.metadata (8.4 kB)
Collecting joblib>=1.2.0 (from scikit-learn<2->mlflow)
  Using cached joblib-1.5.3-py3-none-any.whl.metadata (5.5 kB)
Collecting threadpoolctl>=3.1.0 (from scikit-learn<2->mlflow)
  Using cached threadpoolctl-3.6.0-py3-none-any.whl.metadata (13 kB)
Collecting prettytable>=3.9 (from skops<1->mlflow)
  Using cached prettytable-3.17.0-py3-none-any.whl.metadata (34 kB)
Collecting greenlet>=1 (from sqlalchemy<3,>=1.4.0->mlflow)
  Downloading greenlet-3.3.2-cp310-cp310-win_amd64.whl.metadata (3.8 kB)
Collecting h11>=0.8 (from uvicorn<1->mlflow-skinny==3.10.0->mlflow)
  Using cached h11-0.16.0-py3-none-any.whl.metadata (8.3 kB)
Collecting appdirs>=1.4.4 (from dagshub)
  Using cached appdirs-1.4.4-py2.py3-none-any.whl.metadata (9.0 kB)
Collecting httpx>=0.23.0 (from dagshub)
  Using cached httpx-0.28.1-py3-none-any.whl.metadata (7.1 kB)
Collecting rich>=13.1.0 (from dagshub)
  Using cached rich-14.3.3-py3-none-any.whl.metadata (18 kB)
Collecting dacite~=1.6.0 (from dagshub)
  Using cached dacite-1.6.0-py3-none-any.whl.metadata (14 kB)
Collecting tenacity>=8.2.2 (from dagshub)
  Downloading tenacity-9.1.4-py3-none-any.whl.metadata (1.2 kB)
Collecting gql[requests] (from dagshub)
  Using cached gql-4.0.0-py3-none-any.whl.metadata (10 kB)
Collecting dataclasses-json (from dagshub)
  Using cached dataclasses_json-0.6.7-py3-none-any.whl.metadata (25 kB)
Collecting treelib>=1.6.4 (from dagshub)
  Using cached treelib-1.8.0-py3-none-any.whl.metadata (3.3 kB)
Collecting pathvalidate>=3.0.0 (from dagshub)
  Using cached pathvalidate-3.3.1-py3-none-any.whl.metadata (12 kB)
Collecting boto3 (from dagshub)
  Downloading boto3-1.42.59-py3-none-any.whl.metadata (6.7 kB)
Collecting semver (from dagshub)
  Using cached semver-3.0.4-py3-none-any.whl.metadata (6.8 kB)
Collecting dagshub-annotation-converter>=0.1.12 (from dagshub)
  Downloading dagshub_annotation_converter-0.1.16-py3-none-any.whl.metadata (3.2 kB)
Collecting pycparser (from cffi>=2.0.0->cryptography<47,>=43.0.0->mlflow)
  Using cached pycparser-3.0-py3-none-any.whl.metadata (8.2 kB)
Collecting lxml (from dagshub-annotation-converter>=0.1.12->dagshub)
  Downloading lxml-6.0.2-cp310-cp310-win_amd64.whl.metadata (3.7 kB)
Collecting anyio (from httpx>=0.23.0->dagshub)
  Using cached anyio-4.12.1-py3-none-any.whl.metadata (4.3 kB)
Collecting httpcore==1.* (from httpx>=0.23.0->dagshub)
  Using cached httpcore-1.0.9-py3-none-any.whl.metadata (21 kB)
Collecting wcwidth (from prettytable>=3.9->skops<1->mlflow)
  Using cached wcwidth-0.6.0-py3-none-any.whl.metadata (30 kB)
Collecting markdown-it-py>=2.2.0 (from rich>=13.1.0->dagshub)
  Using cached markdown_it_py-4.0.0-py3-none-any.whl.metadata (7.3 kB)
Collecting pygments<3.0.0,>=2.13.0 (from rich>=13.1.0->dagshub)
  Using cached pygments-2.19.2-py3-none-any.whl.metadata (2.5 kB)
Collecting mdurl~=0.1 (from markdown-it-py>=2.2.0->rich>=13.1.0->dagshub)
  Using cached mdurl-0.1.2-py3-none-any.whl.metadata (1.6 kB)
Collecting exceptiongroup>=1.0.2 (from anyio->httpx>=0.23.0->dagshub)
  Using cached exceptiongroup-1.3.1-py3-none-any.whl.metadata (6.7 kB)
Collecting botocore<1.43.0,>=1.42.59 (from boto3->dagshub)
  Using cached botocore-1.42.59-py3-none-any.whl.metadata (5.9 kB)
Collecting jmespath<2.0.0,>=0.7.1 (from boto3->dagshub)
  Using cached jmespath-1.1.0-py3-none-any.whl.metadata (7.6 kB)
Collecting s3transfer<0.17.0,>=0.16.0 (from boto3->dagshub)
  Using cached s3transfer-0.16.0-py3-none-any.whl.metadata (1.7 kB)
Collecting marshmallow<4.0.0,>=3.18.0 (from dataclasses-json->dagshub)
  Using cached marshmallow-3.26.2-py3-none-any.whl.metadata (7.3 kB)
Collecting typing-inspect<1,>=0.4.0 (from dataclasses-json->dagshub)
  Using cached typing_inspect-0.9.0-py3-none-any.whl.metadata (1.5 kB)
Collecting mypy-extensions>=0.3.0 (from typing-inspect<1,>=0.4.0->dataclasses-json->dagshub)
  Using cached mypy_extensions-1.1.0-py3-none-any.whl.metadata (1.1 kB)
Collecting yarl<2.0,>=1.6 (from gql[requests]->dagshub)
  Using cached yarl-1.22.0-cp310-cp310-win_amd64.whl.metadata (77 kB)
Collecting backoff<3.0,>=1.11.1 (from gql[requests]->dagshub)
  Using cached backoff-2.2.1-py3-none-any.whl.metadata (14 kB)
Collecting requests_toolbelt<2,>=1.0.0 (from gql[requests]->dagshub)
  Using cached requests_toolbelt-1.0.0-py2.py3-none-any.whl.metadata (14 kB)
Collecting multidict>=4.0 (from yarl<2.0,>=1.6->gql[requests]->dagshub)
  Downloading multidict-6.7.1-cp310-cp310-win_amd64.whl.metadata (5.5 kB)
Collecting propcache>=0.2.1 (from yarl<2.0,>=1.6->gql[requests]->dagshub)
  Using cached propcache-0.4.1-cp310-cp310-win_amd64.whl.metadata (14 kB)
Downloading mlflow-3.10.0-py3-none-any.whl (10.2 MB)
   ---------------------------------------- 0.0/10.2 MB ? eta -:--:--
   ---------------------------------------- 0.0/10.2 MB ? eta -:--:--
   - -------------------------------------- 0.3/10.2 MB ? eta -:--:--
   - -------------------------------------- 0.3/10.2 MB ? eta -:--:--
   -- ------------------------------------- 0.5/10.2 MB 672.2 kB/s eta 0:00:15
   --- ------------------------------------ 0.8/10.2 MB 860.9 kB/s eta 0:00:11
   ---- ----------------------------------- 1.0/10.2 MB 915.5 kB/s eta 0:00:10
   ------ --------------------------------- 1.6/10.2 MB 1.3 MB/s eta 0:00:07
   --------- ------------------------------ 2.4/10.2 MB 1.6 MB/s eta 0:00:05
   ----------- ---------------------------- 2.9/10.2 MB 1.8 MB/s eta 0:00:05
   ------------- -------------------------- 3.4/10.2 MB 1.9 MB/s eta 0:00:04
   --------------- ------------------------ 3.9/10.2 MB 1.9 MB/s eta 0:00:04
   ----------------- ---------------------- 4.5/10.2 MB 1.9 MB/s eta 0:00:03
   ------------------- -------------------- 5.0/10.2 MB 2.0 MB/s eta 0:00:03
   --------------------- ------------------ 5.5/10.2 MB 2.0 MB/s eta 0:00:03
   ---------------------- ----------------- 5.8/10.2 MB 2.0 MB/s eta 0:00:03
   ------------------------ --------------- 6.3/10.2 MB 2.0 MB/s eta 0:00:02
   -------------------------- ------------- 6.8/10.2 MB 2.1 MB/s eta 0:00:02
   ---------------------------- ----------- 7.3/10.2 MB 2.1 MB/s eta 0:00:02
   ------------------------------ --------- 7.9/10.2 MB 2.1 MB/s eta 0:00:02
   ------------------------------- -------- 8.1/10.2 MB 2.1 MB/s eta 0:00:01
   ---------------------------------- ----- 8.7/10.2 MB 2.1 MB/s eta 0:00:01
   ------------------------------------ --- 9.2/10.2 MB 2.1 MB/s eta 0:00:01
   ------------------------------------- -- 9.4/10.2 MB 2.1 MB/s eta 0:00:01
   ---------------------------------------  10.0/10.2 MB 2.1 MB/s eta 0:00:01
   ---------------------------------------- 10.2/10.2 MB 2.0 MB/s  0:00:05
Downloading mlflow_skinny-3.10.0-py3-none-any.whl (3.0 MB)
   ---------------------------------------- 0.0/3.0 MB ? eta -:--:--
   --- ------------------------------------ 0.3/3.0 MB ? eta -:--:--
   ------- -------------------------------- 0.5/3.0 MB 2.1 MB/s eta 0:00:02
   -------------- ------------------------- 1.0/3.0 MB 1.9 MB/s eta 0:00:01
   ----------------- ---------------------- 1.3/3.0 MB 1.9 MB/s eta 0:00:01
   ------------------------ --------------- 1.8/3.0 MB 2.0 MB/s eta 0:00:01
   ---------------------------- ----------- 2.1/3.0 MB 2.0 MB/s eta 0:00:01
   ----------------------------------- ---- 2.6/3.0 MB 2.0 MB/s eta 0:00:01
   ---------------------------------------- 3.0/3.0 MB 1.9 MB/s  0:00:01
Downloading mlflow_tracing-3.10.0-py3-none-any.whl (1.5 MB)
   ---------------------------------------- 0.0/1.5 MB ? eta -:--:--
   ------- -------------------------------- 0.3/1.5 MB ? eta -:--:--
   -------------- ------------------------- 0.5/1.5 MB 1.7 MB/s eta 0:00:01
   ---------------------------- ----------- 1.0/1.5 MB 1.8 MB/s eta 0:00:01
   ----------------------------------- ---- 1.3/1.5 MB 1.8 MB/s eta 0:00:01
   ---------------------------------------- 1.5/1.5 MB 1.7 MB/s  0:00:00
Downloading alembic-1.18.4-py3-none-any.whl (263 kB)
Downloading cachetools-7.0.1-py3-none-any.whl (13 kB)
Using cached click-8.3.1-py3-none-any.whl (108 kB)
Using cached cloudpickle-3.1.2-py3-none-any.whl (22 kB)
Downloading cryptography-46.0.5-cp38-abi3-win_amd64.whl (3.5 MB)
   ---------------------------------------- 0.0/3.5 MB ? eta -:--:--
   --- ------------------------------------ 0.3/3.5 MB ? eta -:--:--
   ------ --------------------------------- 0.5/3.5 MB 1.9 MB/s eta 0:00:02
   ------------ --------------------------- 1.0/3.5 MB 1.7 MB/s eta 0:00:02
   --------------- ------------------------ 1.3/3.5 MB 1.7 MB/s eta 0:00:02
   ------------------ --------------------- 1.6/3.5 MB 1.7 MB/s eta 0:00:02
   ------------------------ --------------- 2.1/3.5 MB 1.7 MB/s eta 0:00:01
   --------------------------- ------------ 2.4/3.5 MB 1.7 MB/s eta 0:00:01
   --------------------------------- ------ 2.9/3.5 MB 1.7 MB/s eta 0:00:01
   --------------------------------- ------ 2.9/3.5 MB 1.7 MB/s eta 0:00:01
   ---------------------------------------  3.4/3.5 MB 1.7 MB/s eta 0:00:01
   ---------------------------------------- 3.5/3.5 MB 1.6 MB/s  0:00:02
Downloading databricks_sdk-0.94.0-py3-none-any.whl (811 kB)
   ---------------------------------------- 0.0/811.1 kB ? eta -:--:--
   ------------ --------------------------- 262.1/811.1 kB ? eta -:--:--
   -------------------------------------- - 786.4/811.1 kB 2.2 MB/s eta 0:00:01
   ---------------------------------------- 811.1/811.1 kB 1.8 MB/s  0:00:00
Using cached docker-7.1.0-py3-none-any.whl (147 kB)
Downloading fastapi-0.134.0-py3-none-any.whl (110 kB)
Downloading flask-3.1.3-py3-none-any.whl (103 kB)
Using cached flask_cors-6.0.2-py3-none-any.whl (13 kB)
Using cached gitpython-3.1.46-py3-none-any.whl (208 kB)
Using cached gitdb-4.0.12-py3-none-any.whl (62 kB)
Using cached google_auth-2.48.0-py3-none-any.whl (236 kB)
Using cached graphene-3.4.3-py2.py3-none-any.whl (114 kB)
Using cached graphql_core-3.2.7-py3-none-any.whl (207 kB)
Using cached graphql_relay-3.2.0-py3-none-any.whl (16 kB)
Using cached huey-2.6.0-py3-none-any.whl (76 kB)
Using cached importlib_metadata-8.7.1-py3-none-any.whl (27 kB)
Using cached matplotlib-3.10.8-cp310-cp310-win_amd64.whl (8.1 MB)
Using cached numpy-2.2.6-cp310-cp310-win_amd64.whl (12.9 MB)
Using cached opentelemetry_api-1.39.1-py3-none-any.whl (66 kB)
Using cached opentelemetry_proto-1.39.1-py3-none-any.whl (72 kB)
Using cached opentelemetry_sdk-1.39.1-py3-none-any.whl (132 kB)
Using cached opentelemetry_semantic_conventions-0.60b1-py3-none-any.whl (219 kB)
Using cached packaging-26.0-py3-none-any.whl (74 kB)
Using cached pandas-2.3.3-cp310-cp310-win_amd64.whl (11.3 MB)
Using cached protobuf-6.33.5-cp310-abi3-win_amd64.whl (437 kB)
Downloading pyarrow-23.0.1-cp310-cp310-win_amd64.whl (27.5 MB)
   ---------------------------------------- 0.0/27.5 MB ? eta -:--:--
   ---------------------------------------- 0.3/27.5 MB ? eta -:--:--
   - -------------------------------------- 1.0/27.5 MB 2.5 MB/s eta 0:00:11
   - -------------------------------------- 1.3/27.5 MB 2.4 MB/s eta 0:00:11
   -- ------------------------------------- 1.8/27.5 MB 2.3 MB/s eta 0:00:12
   --- ------------------------------------ 2.4/27.5 MB 2.2 MB/s eta 0:00:12
   --- ------------------------------------ 2.6/27.5 MB 2.2 MB/s eta 0:00:12
   ---- ----------------------------------- 3.1/27.5 MB 2.2 MB/s eta 0:00:12
   ---- ----------------------------------- 3.4/27.5 MB 2.1 MB/s eta 0:00:12
   ----- ---------------------------------- 3.7/27.5 MB 2.1 MB/s eta 0:00:12
   ----- ---------------------------------- 3.9/27.5 MB 1.9 MB/s eta 0:00:13
   ------ --------------------------------- 4.2/27.5 MB 1.8 MB/s eta 0:00:13
   ------ --------------------------------- 4.5/27.5 MB 1.8 MB/s eta 0:00:13
   ------ --------------------------------- 4.7/27.5 MB 1.8 MB/s eta 0:00:13
   ------- -------------------------------- 5.0/27.5 MB 1.7 MB/s eta 0:00:13
   ------- -------------------------------- 5.0/27.5 MB 1.7 MB/s eta 0:00:13
   ------- -------------------------------- 5.2/27.5 MB 1.6 MB/s eta 0:00:15
   -------- ------------------------------- 5.5/27.5 MB 1.6 MB/s eta 0:00:15
   -------- ------------------------------- 6.0/27.5 MB 1.6 MB/s eta 0:00:14
   --------- ------------------------------ 6.3/27.5 MB 1.5 MB/s eta 0:00:14
   --------- ------------------------------ 6.6/27.5 MB 1.5 MB/s eta 0:00:14
   ---------- ----------------------------- 7.1/27.5 MB 1.6 MB/s eta 0:00:14
   ---------- ----------------------------- 7.3/27.5 MB 1.6 MB/s eta 0:00:13
   ----------- ---------------------------- 7.6/27.5 MB 1.6 MB/s eta 0:00:13
   ----------- ---------------------------- 8.1/27.5 MB 1.6 MB/s eta 0:00:13
   ------------ --------------------------- 8.4/27.5 MB 1.6 MB/s eta 0:00:13
   ------------ --------------------------- 8.7/27.5 MB 1.6 MB/s eta 0:00:13
   ------------ --------------------------- 8.7/27.5 MB 1.6 MB/s eta 0:00:13
   ------------ --------------------------- 8.7/27.5 MB 1.6 MB/s eta 0:00:13
   ------------ --------------------------- 8.7/27.5 MB 1.6 MB/s eta 0:00:13
   ------------ --------------------------- 8.7/27.5 MB 1.6 MB/s eta 0:00:13
   ------------ --------------------------- 8.7/27.5 MB 1.6 MB/s eta 0:00:13
   ------------ --------------------------- 8.7/27.5 MB 1.6 MB/s eta 0:00:13
   ------------ --------------------------- 8.7/27.5 MB 1.6 MB/s eta 0:00:13
   ------------ --------------------------- 8.7/27.5 MB 1.6 MB/s eta 0:00:13
   ------------ --------------------------- 8.7/27.5 MB 1.6 MB/s eta 0:00:13
   -------------- ------------------------- 9.7/27.5 MB 1.3 MB/s eta 0:00:15
   -------------- ------------------------- 9.7/27.5 MB 1.3 MB/s eta 0:00:15
   -------------- ------------------------- 9.7/27.5 MB 1.3 MB/s eta 0:00:15
   -------------- ------------------------- 9.7/27.5 MB 1.3 MB/s eta 0:00:15
   --------------- ------------------------ 10.7/27.5 MB 1.2 MB/s eta 0:00:14
   --------------- ------------------------ 10.7/27.5 MB 1.2 MB/s eta 0:00:14
   ---------------- ----------------------- 11.0/27.5 MB 1.2 MB/s eta 0:00:14
   ---------------- ----------------------- 11.0/27.5 MB 1.2 MB/s eta 0:00:14
   ---------------- ----------------------- 11.3/27.5 MB 1.2 MB/s eta 0:00:14
   ---------------- ----------------------- 11.3/27.5 MB 1.2 MB/s eta 0:00:14
   ---------------- ----------------------- 11.3/27.5 MB 1.2 MB/s eta 0:00:14
   ---------------- ----------------------- 11.5/27.5 MB 1.1 MB/s eta 0:00:15
   ----------------- ---------------------- 11.8/27.5 MB 1.1 MB/s eta 0:00:14
   ------------------ --------------------- 12.6/27.5 MB 1.2 MB/s eta 0:00:13
   ------------------- -------------------- 13.1/27.5 MB 1.2 MB/s eta 0:00:12
   ------------------- -------------------- 13.6/27.5 MB 1.2 MB/s eta 0:00:12
   -------------------- ------------------- 14.2/27.5 MB 1.3 MB/s eta 0:00:11
   --------------------- ------------------ 14.7/27.5 MB 1.3 MB/s eta 0:00:10
   ---------------------- ----------------- 15.2/27.5 MB 1.3 MB/s eta 0:00:10
   ---------------------- ----------------- 15.7/27.5 MB 1.3 MB/s eta 0:00:09
   ----------------------- ---------------- 16.0/27.5 MB 1.3 MB/s eta 0:00:09
   ------------------------ --------------- 16.5/27.5 MB 1.4 MB/s eta 0:00:09
   ------------------------ --------------- 17.0/27.5 MB 1.4 MB/s eta 0:00:08
   ------------------------- -------------- 17.3/27.5 MB 1.4 MB/s eta 0:00:08
   ------------------------- -------------- 17.8/27.5 MB 1.4 MB/s eta 0:00:08
   -------------------------- ------------- 18.1/27.5 MB 1.4 MB/s eta 0:00:07
   --------------------------- ------------ 18.6/27.5 MB 1.4 MB/s eta 0:00:07
   --------------------------- ------------ 19.1/27.5 MB 1.4 MB/s eta 0:00:06
   ---------------------------- ----------- 19.7/27.5 MB 1.4 MB/s eta 0:00:06
   ----------------------------- ---------- 20.4/27.5 MB 1.5 MB/s eta 0:00:05
   ------------------------------ --------- 21.0/27.5 MB 1.5 MB/s eta 0:00:05
   ------------------------------- -------- 21.5/27.5 MB 1.5 MB/s eta 0:00:05
   -------------------------------- ------- 22.3/27.5 MB 1.5 MB/s eta 0:00:04
   --------------------------------- ------ 22.8/27.5 MB 1.5 MB/s eta 0:00:04
   --------------------------------- ------ 23.3/27.5 MB 1.6 MB/s eta 0:00:03
   ---------------------------------- ----- 23.9/27.5 MB 1.6 MB/s eta 0:00:03
   ----------------------------------- ---- 24.4/27.5 MB 1.6 MB/s eta 0:00:02
   ------------------------------------ --- 24.9/27.5 MB 1.6 MB/s eta 0:00:02
   ------------------------------------ --- 25.4/27.5 MB 1.6 MB/s eta 0:00:02
   -------------------------------------- - 26.2/27.5 MB 1.6 MB/s eta 0:00:01
   -------------------------------------- - 26.7/27.5 MB 1.6 MB/s eta 0:00:01
   ---------------------------------------  27.3/27.5 MB 1.7 MB/s eta 0:00:01
   ---------------------------------------  27.3/27.5 MB 1.7 MB/s eta 0:00:01
   ---------------------------------------  27.3/27.5 MB 1.7 MB/s eta 0:00:01
   ---------------------------------------- 27.5/27.5 MB 1.6 MB/s  0:00:17
Using cached pydantic-2.12.5-py3-none-any.whl (463 kB)
Using cached pydantic_core-2.41.5-cp310-cp310-win_amd64.whl (2.0 MB)
Using cached python_dateutil-2.9.0.post0-py2.py3-none-any.whl (229 kB)
Using cached python_dotenv-1.2.1-py3-none-any.whl (21 kB)
Using cached pyyaml-6.0.3-cp310-cp310-win_amd64.whl (158 kB)
Using cached requests-2.32.5-py3-none-any.whl (64 kB)
Using cached charset_normalizer-3.4.4-cp310-cp310-win_amd64.whl (107 kB)
Using cached idna-3.11-py3-none-any.whl (71 kB)
Using cached rsa-4.9.1-py3-none-any.whl (34 kB)
Using cached scikit_learn-1.7.2-cp310-cp310-win_amd64.whl (8.9 MB)
Using cached scipy-1.15.3-cp310-cp310-win_amd64.whl (41.3 MB)
Using cached skops-0.13.0-py3-none-any.whl (131 kB)
Using cached smmap-5.0.2-py3-none-any.whl (24 kB)
Downloading sqlalchemy-2.0.47-cp310-cp310-win_amd64.whl (2.1 MB)

In [1]:
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
import pandas as pd
import re
import string
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
import numpy as np

In [2]:
df = pd.read_csv('IMDB.csv')
df = df.sample(500)
df.to_csv('data.csv', index=False)
df.head()

                                                review sentiment
113  "This Man's Navy" is, as other comments have i...  positive
244  If you want a complete waste of time, because ...  negative
2    The `plot' of this film contains a few holes y...  negative
182  As I sat watching this episode I kept glancing...  negative
826  I guess this is the first movie that made me a...  positive

In [3]:
# data preprocessing

# Define text preprocessing functions
def lemmatization(text):
    """Lemmatize the text."""
    lemmatizer = WordNetLemmatizer()
    text = text.split()
    text = [lemmatizer.lemmatize(word) for word in text]
    return " ".join(text)

def remove_stop_words(text):
    """Remove stop words from the text."""
    stop_words = set(stopwords.words("english"))
    text = [word for word in str(text).split() if word not in stop_words]
    return " ".join(text)

def removing_numbers(text):
    """Remove numbers from the text."""
    text = ''.join([char for char in text if not char.isdigit()])
    return text

def lower_case(text):
    """Convert text to lower case."""
    text = text.split()
    text = [word.lower() for word in text]
    return " ".join(text)

def removing_punctuations(text):
    """Remove punctuations from the text."""
    text = re.sub('[%s]' % re.escape(string.punctuation), ' ', text)
    text = text.replace('؛', "")
    text = re.sub('\s+', ' ', text).strip()
    return text

def removing_urls(text):
    """Remove URLs from the text."""
    url_pattern = re.compile(r'https?://\S+|www\.\S+')
    return url_pattern.sub(r'', text)

def normalize_text(df):
    """Normalize the text data."""
    try:
        df['review'] = df['review'].apply(lower_case)
        df['review'] = df['review'].apply(remove_stop_words)
        df['review'] = df['review'].apply(removing_numbers)
        df['review'] = df['review'].apply(removing_punctuations)
        df['review'] = df['review'].apply(removing_urls)
        df['review'] = df['review'].apply(lemmatization)
        return df
    except Exception as e:
        print(f'Error during text normalization: {e}')
        raise

In [4]:
df = normalize_text(df)
df.head()

                                                review sentiment
113  this man s navy is comment indicated rare well...  positive
244  want complete waste time pulling lint belly bu...  negative
2    plot film contains hole could drive massive tr...  negative
182  sat watching episode kept glancing clock waiti...  negative
826  guess first movie made aware term cult flick t...  positive

In [5]:
df['sentiment'].value_counts()

sentiment
negative    267
positive    233
Name: count, dtype: int64

In [6]:
x = df['sentiment'].isin(['positive','negative'])
df = df[x]

In [7]:
df['sentiment'] = df['sentiment'].map({'positive':1, 'negative':0})
df.head()

                                                review  sentiment
113  this man s navy is comment indicated rare well...          1
244  want complete waste time pulling lint belly bu...          0
2    plot film contains hole could drive massive tr...          0
182  sat watching episode kept glancing clock waiti...          0
826  guess first movie made aware term cult flick t...          1

In [8]:
df.isnull().sum()

review       0
sentiment    0
dtype: int64

In [9]:
vectorizer = CountVectorizer(max_features=100)
X = vectorizer.fit_transform(df['review'])
y = df['sentiment']

In [10]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)

In [11]:
import mlflow

c:\Users\Hp\anaconda3\envs\atlas\lib\site-packages\requests\__init__.py:113: RequestsDependencyWarning: urllib3 (2.6.3) or chardet (6.0.0.post1)/charset_normalizer (3.4.4) doesn't match a supported version!
  warnings.warn(
c:\Users\Hp\anaconda3\envs\atlas\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [13]:
import dagshub

mlflow.set_tracking_uri('https://dagshub.com/ajaychaudhary8104/End_to_End_ML_project_for_Sentiment_Classification.mlflow')
dagshub.init(repo_owner='ajaychaudhary8104', repo_name='End_to_End_ML_project_for_Sentiment_Classification', mlflow=True)

# mlflow.set_experiment("Logistic Regression Baseline")
mlflow.set_experiment("Logistic Regression Baseline")

Initialized MLflow to track repo "ajaychaudhary8104/End_to_End_ML_project_for_Sentiment_Classification"

Repository ajaychaudhary8104/End_to_End_ML_project_for_Sentiment_Classification initialized!

2026/02/28 19:51:34 INFO mlflow.tracking.fluent: Experiment with name 'Logistic Regression Baseline' does not exist. Creating a new experiment.

<Experiment: artifact_location='mlflow-artifacts:/0e7c317a1acd491681e239caf551e174', creation_time=1772288494756, experiment_id='0', last_update_time=1772288494756, lifecycle_stage='active', name='Logistic Regression Baseline', tags={}, workspace='default'>

In [14]:
import mlflow
import logging
import os
import time
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

# Configure logging
logging.basicConfig(level=logging.INFO, format="%(asctime)s - %(levelname)s - %(message)s")

logging.info("Starting MLflow run...")

with mlflow.start_run():
    start_time = time.time()
    
    try:
        logging.info("Logging preprocessing parameters...")
        mlflow.log_param("vectorizer", "Bag of Words")
        mlflow.log_param("num_features", 100)
        mlflow.log_param("test_size", 0.25)

        logging.info("Initializing Logistic Regression model...")
        model = LogisticRegression(max_iter=1000)  # Increase max_iter to prevent non-convergence issues

        logging.info("Fitting the model...")
        model.fit(X_train, y_train)
        logging.info("Model training complete.")

        logging.info("Logging model parameters...")
        mlflow.log_param("model", "Logistic Regression")

        logging.info("Making predictions...")
        y_pred = model.predict(X_test)

        logging.info("Calculating evaluation metrics...")
        accuracy = accuracy_score(y_test, y_pred)
        precision = precision_score(y_test, y_pred)
        recall = recall_score(y_test, y_pred)
        f1 = f1_score(y_test, y_pred)

        logging.info("Logging evaluation metrics...")
        mlflow.log_metric("accuracy", accuracy)
        mlflow.log_metric("precision", precision)
        mlflow.log_metric("recall", recall)
        mlflow.log_metric("f1_score", f1)

        logging.info("Saving and logging the model...")
        mlflow.sklearn.log_model(model, "model")

        # Log execution time
        end_time = time.time()
        logging.info(f"Model training and logging completed in {end_time - start_time:.2f} seconds.")

        # Save and log the notebook
        # notebook_path = "exp1_baseline_model.ipynb"
        # logging.info("Executing Jupyter Notebook. This may take a while...")
        # os.system(f"jupyter nbconvert --to notebook --execute --inplace {notebook_path}")
        # mlflow.log_artifact(notebook_path)

        # logging.info("Notebook execution and logging complete.")

        # Print the results for verification
        logging.info(f"Accuracy: {accuracy}")
        logging.info(f"Precision: {precision}")
        logging.info(f"Recall: {recall}")
        logging.info(f"F1 Score: {f1}")

    except Exception as e:
        logging.error(f"An error occurred: {e}", exc_info=True)

2026-02-28 19:52:03,776 - INFO - Starting MLflow run...

2026-02-28 19:52:04,856 - INFO - Logging preprocessing parameters...
2026-02-28 19:52:06,194 - INFO - Initializing Logistic Regression model...
2026-02-28 19:52:06,194 - INFO - Fitting the model...
2026-02-28 19:52:06,263 - INFO - Model training complete.
2026-02-28 19:52:06,265 - INFO - Logging model parameters...
2026-02-28 19:52:06,703 - INFO - Making predictions...
2026-02-28 19:52:06,703 - INFO - Calculating evaluation metrics...
2026-02-28 19:52:06,735 - INFO - Logging evaluation metrics...
2026-02-28 19:52:08,643 - INFO - Saving and logging the model...
2026/02/28 19:52:08 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/02/28 19:52:13 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html
2026-02-28 19:52:31,112 - INFO - Model training and logging completed in 26.26 seconds.
2026-02-28 19:52:31,113 - INFO - Accuracy: 0.608
2026-02-28 19:52:31,114 - INFO - Precision: 0.5352112676056338
2026-02-28 19:52:31,115 - INFO - Recall: 0.7037037037037037
2026-02-28 19:52:31,117 - INFO - F1 Score: 0.608

🏃 View run selective-gull-773 at: https://dagshub.com/ajaychaudhary8104/End_to_End_ML_project_for_Sentiment_Classification.mlflow/#/experiments/0/runs/d7c269315d7d46aeab8e55bfa9c319c3
🧪 View experiment at: https://dagshub.com/ajaychaudhary8104/End_to_End_ML_project_for_Sentiment_Classification.mlflow/#/experiments/0